modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Zitrone_Lemon"
description='''
LEMONS!!!
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
type="optional"
versionRange="[2.0,3.0)"
ordering="NONE"
side="BOTH"

[[dependencies.lemonthings]]
modId="curios"
type="required"
versionRange="[9.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.lemonthings]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="AFTER"
side="BOTH"


